/* ===================================================================
   FLUJO DE EFECTIVO MX · Datos del juego
   -------------------------------------------------------------------
   Todo el contenido editable vive aquí: profesiones, cartas de tratos,
   mercado, gastos imprevistos, tablero, vía rápida y glosario.
   Los montos están en PESOS MEXICANOS (MXN) y son mensuales cuando se
   trata de ingresos, gastos o flujo.

   ¿Quieres cambiar el juego? Edita los arreglos de abajo. No hace falta
   tocar el motor (motor.js) ni la interfaz (juego.js).
   =================================================================== */

window.CF = window.CF || {};

/* ------------------------------------------------------------------
   1. PROFESIONES
   ------------------------------------------------------------------
   salario      : ingreso mensual neto aproximado
   ahorros      : efectivo con el que empiezas
   gastoPorHijo : lo que te cuesta cada hijo al mes
   gastos       : [{ id, nombre, monto, pasivo? }]
                  Si un gasto trae "pasivo", se puede liquidar pagando
                  el saldo completo (y entonces desaparece el gasto).
   ------------------------------------------------------------------ */
const PROFESIONES = [
  {
    id: "maestra-sep",
    nombre: "Maestra de primaria (SEP)",
    emoji: "🍎",
    resumen: "Plaza federal, quincena puntual y un Infonavit de por vida.",
    salario: 17500,
    ahorros: 25000,
    gastoPorHijo: 1900,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 2100 },
      { id: "infonavit", nombre: "Crédito Infonavit", monto: 2400, pasivo: { nombre: "Saldo Infonavit", saldo: 610000 } },
      { id: "tarjeta", nombre: "Tarjeta de crédito", monto: 700, pasivo: { nombre: "Deuda de tarjeta", saldo: 21000 } },
      { id: "departamental", nombre: "Tienda departamental (Coppel)", monto: 600, pasivo: { nombre: "Deuda departamental", saldo: 14000 } },
      { id: "varios", nombre: "Gastos varios (despensa, luz, transporte)", monto: 5600 },
    ],
  },
  {
    id: "enfermero-imss",
    nombre: "Enfermero(a) del IMSS",
    emoji: "🩺",
    resumen: "Turnos, guardias y un Fonacot que se antojó fácil.",
    salario: 21000,
    ahorros: 30000,
    gastoPorHijo: 2000,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 2600 },
      { id: "infonavit", nombre: "Crédito Infonavit", monto: 2900, pasivo: { nombre: "Saldo Infonavit", saldo: 720000 } },
      { id: "auto", nombre: "Crédito automotriz", monto: 2300, pasivo: { nombre: "Saldo del auto", saldo: 118000 } },
      { id: "tarjeta", nombre: "Tarjeta de crédito", monto: 900, pasivo: { nombre: "Deuda de tarjeta", saldo: 26000 } },
      { id: "fonacot", nombre: "Crédito Fonacot", monto: 700, pasivo: { nombre: "Saldo Fonacot", saldo: 18000 } },
      { id: "varios", nombre: "Gastos varios", monto: 5800 },
    ],
  },
  {
    id: "chofer-app",
    nombre: "Chofer de app (Uber / DiDi)",
    emoji: "🚗",
    resumen: "Tú pones el coche, la gasolina y las horas. El margen es delgadito.",
    salario: 19500,
    ahorros: 18000,
    gastoPorHijo: 1700,
    gastos: [
      { id: "isr", nombre: "Impuestos (RESICO)", monto: 800 },
      { id: "renta", nombre: "Renta de la vivienda", monto: 5500 },
      { id: "auto", nombre: "Crédito automotriz (tu herramienta de trabajo)", monto: 4200, pasivo: { nombre: "Saldo del auto", saldo: 190000 } },
      { id: "tarjeta", nombre: "Tarjeta de crédito", monto: 800, pasivo: { nombre: "Deuda de tarjeta", saldo: 22000 } },
      { id: "departamental", nombre: "Tienda departamental (Elektra)", monto: 600, pasivo: { nombre: "Deuda departamental", saldo: 11000 } },
      { id: "varios", nombre: "Gastos varios", monto: 3200 },
    ],
  },
  {
    id: "policia-municipal",
    nombre: "Policía municipal",
    emoji: "👮",
    resumen: "Sueldo modesto, prestaciones decentes y muchas horas extra.",
    salario: 15800,
    ahorros: 20000,
    gastoPorHijo: 1800,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 1500 },
      { id: "infonavit", nombre: "Crédito Infonavit", monto: 2200, pasivo: { nombre: "Saldo Infonavit", saldo: 540000 } },
      { id: "auto", nombre: "Crédito automotriz", monto: 1900, pasivo: { nombre: "Saldo del auto", saldo: 95000 } },
      { id: "tarjeta", nombre: "Tarjeta de crédito", monto: 600, pasivo: { nombre: "Deuda de tarjeta", saldo: 17000 } },
      { id: "departamental", nombre: "Tienda departamental (Coppel)", monto: 700, pasivo: { nombre: "Deuda departamental", saldo: 15000 } },
      { id: "varios", nombre: "Gastos varios", monto: 4400 },
    ],
  },
  {
    id: "duena-papeleria",
    nombre: "Dueña de papelería",
    emoji: "🏪",
    resumen: "Negocio propio... que en realidad es un autoempleo. Si no abres, no entra.",
    salario: 26000,
    ahorros: 35000,
    gastoPorHijo: 2200,
    gastos: [
      { id: "isr", nombre: "Impuestos (RESICO)", monto: 1100 },
      { id: "renta", nombre: "Renta del local + vivienda", monto: 7800 },
      { id: "auto", nombre: "Crédito automotriz", monto: 2600, pasivo: { nombre: "Saldo del auto", saldo: 140000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 1300, pasivo: { nombre: "Deuda de tarjetas", saldo: 42000 } },
      { id: "financiera", nombre: "Préstamo de financiera para inventario", monto: 1800, pasivo: { nombre: "Saldo con la financiera", saldo: 55000 } },
      { id: "varios", nombre: "Gastos varios", monto: 4900 },
    ],
  },
  {
    id: "arquitecto",
    nombre: "Arquitecto en despacho",
    emoji: "📐",
    resumen: "Buen puesto, buen currículum... y una renta que se come el sueldo.",
    salario: 31000,
    ahorros: 40000,
    gastoPorHijo: 2500,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 4100 },
      { id: "renta", nombre: "Renta del departamento", monto: 8500 },
      { id: "auto", nombre: "Crédito automotriz", monto: 3400, pasivo: { nombre: "Saldo del auto", saldo: 180000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 1600, pasivo: { nombre: "Deuda de tarjetas", saldo: 55000 } },
      { id: "educativo", nombre: "Crédito educativo (titulación y maestría)", monto: 1100, pasivo: { nombre: "Saldo del crédito educativo", saldo: 52000 } },
      { id: "varios", nombre: "Gastos varios", monto: 5300 },
    ],
  },
  {
    id: "contador",
    nombre: "Contador público",
    emoji: "🧮",
    resumen: "Sabes de números, pero el SAT y las tarjetas también saben de ti.",
    salario: 28000,
    ahorros: 45000,
    gastoPorHijo: 2600,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 4600 },
      { id: "infonavit", nombre: "Crédito Infonavit", monto: 3600, pasivo: { nombre: "Saldo Infonavit", saldo: 890000 } },
      { id: "auto", nombre: "Crédito automotriz", monto: 3900, pasivo: { nombre: "Saldo del auto", saldo: 215000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 1400, pasivo: { nombre: "Deuda de tarjetas", saldo: 48000 } },
      { id: "educativo", nombre: "Crédito educativo", monto: 1300, pasivo: { nombre: "Saldo del crédito educativo", saldo: 65000 } },
      { id: "varios", nombre: "Gastos varios", monto: 6900 },
    ],
  },
  {
    id: "ing-civil",
    nombre: "Ingeniero civil (residente de obra)",
    emoji: "🏗️",
    resumen: "Buen ingreso mientras haya obra. Cuando no hay obra, no hay nada.",
    salario: 34000,
    ahorros: 55000,
    gastoPorHijo: 3000,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 5600 },
      { id: "infonavit", nombre: "Crédito Infonavit + Cofinavit", monto: 4300, pasivo: { nombre: "Saldo hipotecario", saldo: 1050000 } },
      { id: "auto", nombre: "Crédito automotriz (camioneta)", monto: 5200, pasivo: { nombre: "Saldo del auto", saldo: 290000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 1800, pasivo: { nombre: "Deuda de tarjetas", saldo: 62000 } },
      { id: "varios", nombre: "Gastos varios", monto: 8100 },
    ],
  },
  {
    id: "abogada",
    nombre: "Abogada corporativa",
    emoji: "⚖️",
    resumen: "Facturas alto y gastas alto. El estilo de vida sube más rápido que el sueldo.",
    salario: 42000,
    ahorros: 60000,
    gastoPorHijo: 3600,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 6900 },
      { id: "hipoteca", nombre: "Hipoteca bancaria", monto: 7400, pasivo: { nombre: "Saldo hipotecario", saldo: 1380000 } },
      { id: "auto", nombre: "Crédito automotriz", monto: 5800, pasivo: { nombre: "Saldo del auto", saldo: 300000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 2900, pasivo: { nombre: "Deuda de tarjetas", saldo: 98000 } },
      { id: "educativo", nombre: "Crédito educativo (maestría)", monto: 2000, pasivo: { nombre: "Saldo del crédito educativo", saldo: 120000 } },
      { id: "varios", nombre: "Gastos varios", monto: 8000 },
    ],
  },
  {
    id: "medico-general",
    nombre: "Médico general",
    emoji: "👨‍⚕️",
    resumen: "Años de estudio, deuda educativa larga y consultorio que apenas arranca.",
    salario: 50000,
    ahorros: 65000,
    gastoPorHijo: 4000,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 8000 },
      { id: "hipoteca", nombre: "Hipoteca bancaria", monto: 8600, pasivo: { nombre: "Saldo hipotecario", saldo: 1620000 } },
      { id: "auto", nombre: "Crédito automotriz", monto: 6900, pasivo: { nombre: "Saldo del auto", saldo: 380000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 3100, pasivo: { nombre: "Deuda de tarjetas", saldo: 110000 } },
      { id: "educativo", nombre: "Crédito educativo (carrera y especialidad)", monto: 3400, pasivo: { nombre: "Saldo del crédito educativo", saldo: 260000 } },
      { id: "varios", nombre: "Gastos varios", monto: 9000 },
    ],
  },
  {
    id: "dev-software",
    nombre: "Desarrollador de software",
    emoji: "💻",
    resumen: "Sueldo alto en pesos, gastos hormiga en dólares (y muchas suscripciones).",
    salario: 52000,
    ahorros: 90000,
    gastoPorHijo: 4200,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 9700 },
      { id: "hipoteca", nombre: "Hipoteca bancaria", monto: 9800, pasivo: { nombre: "Saldo hipotecario", saldo: 1850000 } },
      { id: "auto", nombre: "Crédito automotriz", monto: 6400, pasivo: { nombre: "Saldo del auto", saldo: 340000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 2600, pasivo: { nombre: "Deuda de tarjetas", saldo: 95000 } },
      { id: "varios", nombre: "Suscripciones y gastos varios", monto: 11500 },
    ],
  },
  {
    id: "piloto",
    nombre: "Piloto aviador",
    emoji: "✈️",
    resumen: "El ingreso más alto del tablero... y también el estilo de vida más caro.",
    salario: 85000,
    ahorros: 100000,
    gastoPorHijo: 6500,
    gastos: [
      { id: "isr", nombre: "ISR e IMSS (retenciones)", monto: 16500 },
      { id: "hipoteca", nombre: "Hipoteca bancaria", monto: 14000, pasivo: { nombre: "Saldo hipotecario", saldo: 2750000 } },
      { id: "auto", nombre: "Crédito automotriz", monto: 9500, pasivo: { nombre: "Saldo del auto", saldo: 520000 } },
      { id: "tarjeta", nombre: "Tarjetas de crédito", monto: 4500, pasivo: { nombre: "Deuda de tarjetas", saldo: 150000 } },
      { id: "colegiaturas", nombre: "Colegiaturas y gastos varios", monto: 21500 },
    ],
  },
];

/* ------------------------------------------------------------------
   2. TRATOS PEQUEÑOS  (inversiones de entrada, "small deals")
   ------------------------------------------------------------------
   tipo: acciones | renta-fija | inmueble | negocio | salario
   ------------------------------------------------------------------ */
const TRATOS_PEQUENOS = [
  /* --- Renta fija: lo primero que casi todos tocamos en México --- */
  { id: "tp-cetes28", tipo: "renta-fija", titulo: "CETES a 28 días (cetesdirecto)",
    texto: "Abres tu cuenta en cetesdirecto desde el celular y colocas tu ahorro en Certificados de la Tesorería.",
    monto: 50000, tasaAnual: 0.085, riesgo: "bajo",
    nota: "Es deuda del gobierno federal: el activo más seguro en pesos. No te hará rico, pero le gana a la cuenta de nómina." },
  { id: "tp-cetes1a", tipo: "renta-fija", titulo: "CETES a 1 año",
    texto: "Amarras la tasa a 12 meses. Si Banxico baja las tasas, tú ya la aseguraste.",
    monto: 100000, tasaAnual: 0.088, riesgo: "bajo",
    nota: "Plazo más largo = tasa más alta, pero tu dinero queda comprometido. Eso se llama riesgo de liquidez." },
  { id: "tp-pagare", tipo: "renta-fija", titulo: "Pagaré bancario a 90 días",
    texto: "El banco donde tienes tu nómina te ofrece un pagaré con tasa preferencial.",
    monto: 30000, tasaAnual: 0.062, riesgo: "bajo",
    nota: "Casi siempre paga menos que CETES porque el banco se queda el diferencial. Compara antes de firmar." },
  { id: "tp-pagare-alto", tipo: "renta-fija", titulo: "Pagaré de banco de nicho (tasa alta)",
    texto: "Un banco pequeño ofrece 11% anual. Está protegido por el IPAB hasta cierto monto.",
    monto: 20000, tasaAnual: 0.11, riesgo: "medio",
    nota: "Tasa alta = más riesgo del emisor. El IPAB cubre hasta 400 mil UDIs por persona por banco." },
  { id: "tp-udibonos", tipo: "renta-fija", titulo: "Udibonos a 3 años",
    texto: "Instrumento ligado a la inflación (UDIs): protege tu poder adquisitivo.",
    monto: 100000, tasaAnual: 0.098, riesgo: "bajo",
    nota: "Su gracia es que la inflación no te come el rendimiento. Ideal para dinero de largo plazo." },
  { id: "tp-fondo-deuda", tipo: "renta-fija", titulo: "Fondo de deuda gubernamental (liquidez diaria)",
    texto: "Un fondo de inversión que puedes retirar el mismo día.",
    monto: 40000, tasaAnual: 0.091, riesgo: "bajo",
    nota: "Buen lugar para tu fondo de emergencia: rinde y lo puedes sacar rápido." },
  { id: "tp-factoraje", tipo: "renta-fija", titulo: "Factoraje: compras una factura con descuento",
    texto: "Un proveedor necesita liquidez y te cede el cobro de una factura a 90 días.",
    monto: 60000, tasaAnual: 0.23, riesgo: "alto",
    nota: "Rinde mucho porque asumes el riesgo de que el cliente no pague. Nunca metas aquí tu fondo de emergencia." },
  { id: "tp-crowdfunding", tipo: "renta-fija", titulo: "Crowdfunding inmobiliario (M2Crowd / 100 Ladrillos)",
    texto: "Con poco dinero entras a un proyecto inmobiliario junto con otros inversionistas.",
    monto: 25000, tasaAnual: 0.10, riesgo: "medio",
    nota: "Ley Fintech regula estas plataformas, pero el proyecto puede atrasarse. Diversifica en varios." },
  { id: "tp-prestamo-compadre", tipo: "renta-fija", titulo: "Le prestas a tu compadre (con pagaré firmado)",
    texto: "Tu compadre necesita capital para su taller y te ofrece pagarte con intereses. Firman pagaré ante notario.",
    monto: 40000, tasaAnual: 0.30, riesgo: "alto",
    nota: "Prestar a conocidos mezcla dinero y afecto. Si lo haces: documento firmado, plazo claro y monto que puedas perder." },

  /* --- Acciones y ETFs de la BMV --- */
  { id: "tp-naftrac", tipo: "acciones", ticker: "NAFTRAC", nombre: "ETF que replica el IPC de la Bolsa Mexicana",
    texto: "Con un solo título compras un pedacito de las 35 empresas más grandes de México.",
    precio: 58, dividendoMensual: 0.24, rango: [38, 95], riesgo: "medio",
    nota: "Diversificación instantánea y comisiones bajas. El clásico primer paso en bolsa." },
  { id: "tp-amxl", tipo: "acciones", ticker: "AMXL", nombre: "América Móvil",
    texto: "La telefónica más grande de la región. Paga dividendo dos veces al año.",
    precio: 17, dividendoMensual: 0.07, rango: [9, 28], riesgo: "medio",
    nota: "Empresa madura: crece poco pero reparte dividendos. Precio barato por acción, ideal para acumular." },
  { id: "tp-walmex", tipo: "acciones", ticker: "WALMEX", nombre: "Walmart de México",
    texto: "Bodega Aurrerá, Sam's y Walmart. Vende despensa, llueva o truene.",
    precio: 62, dividendoMensual: 0.28, rango: [40, 98], riesgo: "medio",
    nota: "Negocio defensivo: la gente come en crisis y en bonanza. Por eso cotiza caro." },
  { id: "tp-cemex", tipo: "acciones", ticker: "CEMEXCPO", nombre: "Cemex",
    texto: "Cementera global, muy sensible al ciclo de la construcción.",
    precio: 12, dividendoMensual: 0, rango: [4, 32], riesgo: "alto",
    nota: "Cíclica y volátil: puede triplicar o partirse a la mitad. Se gana comprando barato, no comprando de moda." },
  { id: "tp-gapb", tipo: "acciones", ticker: "GAPB", nombre: "Grupo Aeroportuario del Pacífico",
    texto: "Opera los aeropuertos de Guadalajara, Tijuana y Los Cabos.",
    precio: 320, dividendoMensual: 1.7, rango: [180, 520], riesgo: "medio",
    nota: "Concesiones de largo plazo con ingresos en dólares. Gran pagadora de dividendos." },
  { id: "tp-volar", tipo: "acciones", ticker: "VOLARA", nombre: "Volaris",
    texto: "Aerolínea de bajo costo. Sube y baja con el turbosina y el tipo de cambio.",
    precio: 9, dividendoMensual: 0, rango: [3, 26], riesgo: "alto",
    nota: "Las aerolíneas son negocios de margen delgadito. Especulación pura." },
  { id: "tp-etf-btc", tipo: "acciones", ticker: "IBIT", nombre: "ETF de bitcoin listado en el SIC",
    texto: "Desde tu casa de bolsa puedes comprar el ETF de bitcoin a través del Sistema Internacional de Cotizaciones.",
    precio: 1100, dividendoMensual: 0, rango: [300, 3800], riesgo: "muy alto",
    nota: "Sin flujo, sin dividendo: solo apuestas al precio. Si entras, que sea con dinero que puedas perder." },

  /* --- FIBRAs: bienes raíces en la bolsa --- */
  { id: "tp-funo", tipo: "acciones", ticker: "FUNO11", nombre: "FIBRA Uno (centros comerciales y naves)",
    texto: "Un fideicomiso dueño de cientos de inmuebles que reparte las rentas entre sus tenedores.",
    precio: 26, dividendoMensual: 0.19, rango: [15, 42], riesgo: "medio",
    nota: "Las FIBRAs deben repartir al menos 95% de su resultado fiscal. Son bienes raíces sin tener que destapar caños." },
  { id: "tp-fmty", tipo: "acciones", ticker: "FMTY14", nombre: "FIBRA Mty (oficinas e industrial)",
    texto: "FIBRA regiomontana, muy expuesta al nearshoring del norte del país.",
    precio: 12.5, dividendoMensual: 0.095, rango: [7, 22], riesgo: "medio",
    nota: "Ingresos en dólares por naves industriales: cobertura natural contra el tipo de cambio." },
  { id: "tp-danhos", tipo: "acciones", ticker: "DANHOS13", nombre: "FIBRA Danhos (plazas premium)",
    texto: "Dueña de plazas como Parque Delta y Toreo. Rentas de alto nivel.",
    precio: 26, dividendoMensual: 0.18, rango: [14, 40], riesgo: "medio",
    nota: "Menos inmuebles pero de mejor calidad. Concentración = más riesgo si a una plaza le va mal." },

  /* --- Inmuebles de entrada --- */
  { id: "tp-casa-tizayuca", tipo: "inmueble", subtipo: "casa", titulo: "Casa de interés social en Tizayuca, Hidalgo",
    texto: "Casa de 60 m² cerca del corredor industrial. Se renta rápido a familias jóvenes.",
    precio: 720000, enganche: 90000, flujo: 3400, riesgo: "medio",
    nota: "Con Infonavit o Cofinavit el enganche es bajo. Ojo con la plusvalía: en conjuntos lejanos suele ser lenta." },
  { id: "tp-depto-gdl", tipo: "inmueble", subtipo: "depto", titulo: "Departamento usado en Guadalajara",
    texto: "Dos recámaras cerca de una universidad. El inquilino anterior ya se va.",
    precio: 1150000, enganche: 200000, flujo: 7500, riesgo: "medio",
    nota: "Regla rápida: renta anual ÷ precio = rendimiento bruto. Menos de 5% en México casi siempre es mal negocio." },
  { id: "tp-estudio-puebla", tipo: "inmueble", subtipo: "depto", titulo: "Estudio para estudiantes en Puebla (de contado)",
    texto: "Un cuarto amueblado a dos cuadras de la universidad. Lo pagas de contado, sin hipoteca.",
    precio: 380000, enganche: 380000, flujo: 5600, riesgo: "medio",
    nota: "Sin deuda, todo el flujo es tuyo. Pero cuidado: en vacaciones se queda vacío." },
  { id: "tp-remate", tipo: "inmueble", subtipo: "casa", titulo: "Casa adjudicada (remate bancario) en Monterrey",
    texto: "El banco recuperó la casa y la vende 30% abajo de su valor comercial. Hay que sacar al ocupante.",
    precio: 850000, enganche: 130000, flujo: 5100, riesgo: "alto",
    nota: "En los remates ganas al comprar, no al vender. El riesgo real es el trámite legal y el desalojo." },
  { id: "tp-terreno-tulum", tipo: "inmueble", subtipo: "terreno", titulo: "Terreno de 200 m² cerca de Tulum",
    texto: "Zona en crecimiento junto al Tren Maya. No genera renta, pero la plusvalía va rápido.",
    precio: 380000, enganche: 380000, flujo: 0, riesgo: "alto",
    nota: "Un terreno sin renta es un gasto disfrazado de activo: pagas predial y no entra nada. Solo sirve si lo vendes bien." },
  { id: "tp-terreno-bajio", tipo: "inmueble", subtipo: "terreno", titulo: "Terreno regularizado en el Bajío",
    texto: "A 15 minutos de un parque industrial nuevo. Escrituras en orden.",
    precio: 250000, enganche: 250000, flujo: 0, riesgo: "medio",
    nota: "Verifica SIEMPRE el régimen de propiedad: los terrenos ejidales sin regularizar son el clásico fraude." },
  { id: "tp-cajon", tipo: "inmueble", subtipo: "estacionamiento", titulo: "Cajón de estacionamiento en el centro",
    texto: "Un cajón con escrituras en un edificio de oficinas. Renta mensual fija.",
    precio: 180000, enganche: 180000, flujo: 2900, riesgo: "bajo",
    nota: "Inmueble chiquito, mantenimiento casi nulo y 10% anual. Los activos aburridos suelen ser los mejores." },
  { id: "tp-bodega-mini", tipo: "inmueble", subtipo: "bodega", titulo: "Mini bodega de autoalmacenamiento",
    texto: "Compras dos bodegas chicas dentro de una nave de self storage ya operando.",
    precio: 260000, enganche: 100000, flujo: 3900, riesgo: "medio",
    nota: "El self storage es de los negocios inmobiliarios más nobles: pocos inquilinos problemáticos y contratos cortos." },

  /* --- Negocios pequeños --- */
  { id: "tp-vending", tipo: "negocio", subtipo: "servicio", titulo: "Máquina expendedora en un corporativo",
    texto: "Compras la máquina, negocias el espacio y surtes cada semana.",
    precio: 45000, enganche: 45000, flujo: 1600, riesgo: "medio",
    nota: "24% anual suena increíble, pero cuenta tu tiempo de resurtido: si tú la surtes, es empleo, no activo." },
  { id: "tp-lavanderia-socio", tipo: "negocio", subtipo: "servicio", titulo: "Socio en una lavandería de autoservicio",
    texto: "Entras con el 25% del capital de una lavandería que ya opera en una colonia céntrica.",
    precio: 90000, enganche: 90000, flujo: 3100, riesgo: "medio",
    nota: "Ser socio minoritario es cómodo, pero no controlas las decisiones. Que quede por escrito cómo se reparte." },
  { id: "tp-tacos", tipo: "negocio", subtipo: "alimentos", titulo: "Puesto de tacos con un socio operador",
    texto: "Tú pones el equipo y el punto; tu socio opera y se queda con la mitad de la utilidad.",
    precio: 70000, enganche: 70000, flujo: 3000, riesgo: "alto",
    nota: "Los negocios de comida dan flujo alto y mueren rápido. Recupera tu inversión en menos de 3 años o no entres." },
  { id: "tp-camioneta", tipo: "negocio", subtipo: "transporte", titulo: "Camioneta rentada a un repartidor",
    texto: "Compras una van usada y la rentas por semana a un repartidor de paquetería.",
    precio: 260000, enganche: 100000, flujo: 4500, riesgo: "alto",
    nota: "Los vehículos se deprecian: tu activo vale menos cada año. Aparta dinero para mantenimiento y seguro." },
  { id: "tp-cafe-movil", tipo: "negocio", subtipo: "alimentos", titulo: "Franquicia de café móvil",
    texto: "Carrito de café de especialidad con marca, capacitación y proveedores.",
    precio: 150000, enganche: 150000, flujo: 5000, riesgo: "medio",
    nota: "La franquicia te vende un sistema probado. Lee la Circular de Oferta Franquicia antes de firmar." },
  { id: "tp-paneles", tipo: "negocio", subtipo: "servicio", titulo: "Paneles solares para un local rentado",
    texto: "Instalas paneles en un local que rentas a un tercero y le cobras la energía.",
    precio: 120000, enganche: 120000, flujo: 2600, riesgo: "bajo",
    nota: "Activo con contrato de largo plazo y mantenimiento mínimo. El pago se recupera en unos 5 años." },

  /* --- Inversiones en ti mismo --- */
  { id: "tp-pmp", tipo: "salario", titulo: "Certificación profesional (PMP / especialidad)",
    texto: "Pagas el curso y el examen. Al certificarte, tu empresa te sube el sueldo.",
    costo: 32000, aumento: 2800,
    nota: "Sube tu ingreso ACTIVO, no el pasivo: si dejas de trabajar, se acaba. Aun así, más ingreso = más municiones para invertir." },
  { id: "tp-ingles", tipo: "salario", titulo: "Inglés + certificación internacional",
    texto: "Un año de clases y el examen. Te abre puestos con clientes en Estados Unidos.",
    costo: 24000, aumento: 2200,
    nota: "El mejor retorno del tablero en porcentaje... pero recuerda: sigue siendo cambiar tiempo por dinero." },
];

/* ------------------------------------------------------------------
   3. TRATOS GRANDES  ("big deals": requieren capital y dan flujo fuerte)
   ------------------------------------------------------------------ */
const TRATOS_GRANDES = [
  { id: "tg-cuadruplex-merida", tipo: "inmueble", subtipo: "plex", titulo: "Cuádruplex en Mérida",
    texto: "Cuatro departamentos en un solo predio, tres ya rentados. Zona norte en expansión.",
    precio: 3600000, enganche: 600000, flujo: 24000, riesgo: "medio",
    nota: "Varias unidades en un solo terreno: si se va un inquilino, todavía te pagan los otros tres." },
  { id: "tg-edificio-gdl", tipo: "inmueble", subtipo: "plex", titulo: "Edificio de 8 departamentos en Guadalajara",
    texto: "Edificio completo, ocupación del 90%, administrado por una inmobiliaria local.",
    precio: 8900000, enganche: 1500000, flujo: 63000, riesgo: "medio",
    nota: "A partir de 5 unidades ya puedes pagar administración profesional y volverlo verdaderamente pasivo." },
  { id: "tg-preventa-cdmx", tipo: "inmueble", subtipo: "depto", titulo: "Departamento en preventa (Narvarte, CDMX)",
    texto: "Compras en obra negra con descuento; entregan en 18 meses y entonces empieza la renta.",
    precio: 3200000, enganche: 550000, flujo: 19500, riesgo: "alto",
    nota: "En preventa ganas descuento a cambio del riesgo de que la desarrolladora no entregue. Investiga su historial." },
  { id: "tg-airbnb-tulum", tipo: "inmueble", subtipo: "depto", titulo: "Departamento amueblado para renta vacacional en Tulum",
    texto: "Listo para Airbnb, con administración incluida. Alta temporada de diciembre a abril.",
    precio: 2800000, enganche: 560000, flujo: 25500, riesgo: "alto",
    nota: "La renta vacacional paga más que la tradicional, pero la ocupación es estacional y hay más regulación cada año." },
  { id: "tg-local-qro", tipo: "inmueble", subtipo: "local", titulo: "Local comercial en plaza de Querétaro",
    texto: "Local de 90 m² con contrato de arrendamiento a 5 años con una cadena de farmacias.",
    precio: 2200000, enganche: 450000, flujo: 18000, riesgo: "medio",
    nota: "Un contrato largo con un inquilino sólido vale oro: te da flujo predecible por años." },
  { id: "tg-bodega-bajio", tipo: "inmueble", subtipo: "bodega", titulo: "Bodega industrial en el Bajío (nearshoring)",
    texto: "Nave de 1,200 m² rentada en dólares a un proveedor automotriz.",
    precio: 6500000, enganche: 1100000, flujo: 46500, riesgo: "medio",
    nota: "Renta en dólares = cobertura contra el tipo de cambio. Es el activo estrella de la relocalización industrial." },
  { id: "tg-casa-zapopan", tipo: "inmueble", subtipo: "casa", titulo: "Casa en fraccionamiento de Zapopan",
    texto: "Casa de 3 recámaras en coto privado. Familia con contrato a dos años.",
    precio: 2600000, enganche: 480000, flujo: 15800, riesgo: "bajo",
    nota: "Rendimiento modesto pero muy estable. Las casas familiares tienen inquilinos que duran más." },
  { id: "tg-terreno-carretera", tipo: "inmueble", subtipo: "terreno", titulo: "Hectárea sobre la carretera federal",
    texto: "Terreno con frente a carretera en zona de crecimiento turístico. De contado.",
    precio: 2400000, enganche: 2400000, flujo: 0, riesgo: "alto",
    nota: "Cero flujo y sí pagas predial. Es una apuesta de plusvalía pura: necesitas aguantar años." },
  { id: "tg-gasolinera", tipo: "negocio", subtipo: "servicio", titulo: "Socio en una gasolinera con franquicia",
    texto: "Entras como socio del 30% en una estación con buen aforo sobre avenida principal.",
    precio: 4500000, enganche: 4500000, flujo: 110000, riesgo: "alto",
    nota: "Margen por litro regulado y mucho capital atrapado. Depende totalmente del volumen de la ubicación." },
  { id: "tg-lavanderias", tipo: "negocio", subtipo: "servicio", titulo: "Cadena de 3 lavanderías de autoservicio",
    texto: "Tres sucursales operando con encargados y sistema de control.",
    precio: 1900000, enganche: 1900000, flujo: 55000, riesgo: "medio",
    nota: "13% anual con equipos que duran una década. Poco glamuroso, muy rentable." },
  { id: "tg-franquicia", tipo: "negocio", subtipo: "alimentos", titulo: "Franquicia de comida rápida (local en plaza)",
    texto: "Marca reconocida, capacitación y proveeduría. Tú contratas gerente.",
    precio: 3500000, enganche: 3500000, flujo: 100000, riesgo: "medio",
    nota: "Pagas regalías mensuales a cambio de una marca que ya jala clientes. Revisa el retorno prometido con lupa." },
  { id: "tg-maquinaria", tipo: "negocio", subtipo: "transporte", titulo: "Renta de maquinaria para construcción",
    texto: "Retroexcavadora y revolvedoras rentadas a constructoras de la región.",
    precio: 2700000, enganche: 700000, flujo: 31500, riesgo: "alto",
    nota: "Si la obra pública se frena, tu maquinaria se queda parada y el crédito sigue corriendo." },
  { id: "tg-hotel-oaxaca", tipo: "negocio", subtipo: "hotel", titulo: "Hotel boutique de 8 habitaciones en Oaxaca",
    texto: "Casona restaurada en el centro histórico, con operación a cargo de un socio local.",
    precio: 5800000, enganche: 1200000, flujo: 51000, riesgo: "alto",
    nota: "La hotelería es operación intensa: no es renta pasiva, es un negocio con edificio adentro." },
  { id: "tg-selfstorage", tipo: "inmueble", subtipo: "bodega", titulo: "Nave de self storage (60 bodegas)",
    texto: "Nave dividida en bodegas chicas, con 80% de ocupación y acceso 24/7.",
    precio: 7200000, enganche: 1400000, flujo: 58500, riesgo: "medio",
    nota: "Muchos inquilinos chiquitos: si se va uno, casi no lo sientes. Diversificación dentro de un mismo inmueble." },
  { id: "tg-cartera", tipo: "negocio", subtipo: "servicio", titulo: "Compra de cartera de créditos",
    texto: "Adquieres un paquete de créditos al consumo con descuento y cobras la recuperación.",
    precio: 1200000, enganche: 1200000, flujo: 40000, riesgo: "alto",
    nota: "14% anual si cobras bien. La cobranza es el negocio; si no sabes cobrar, no compres cartera." },
  { id: "tg-invernadero", tipo: "negocio", subtipo: "agro", titulo: "Campo con invernadero en Sinaloa",
    texto: "Cinco hectáreas con invernadero de tomate y contrato de exportación.",
    precio: 4800000, enganche: 1000000, flujo: 43500, riesgo: "alto",
    nota: "El agro depende del clima, de las plagas y del precio internacional. Alta recompensa, alta incertidumbre." },
  { id: "tg-estacionamiento", tipo: "inmueble", subtipo: "estacionamiento", titulo: "Estacionamiento público en el centro",
    texto: "Predio con 60 cajones, pensión mensual y cobro por hora. De contado.",
    precio: 3100000, enganche: 3100000, flujo: 60000, riesgo: "bajo",
    nota: "Casi sin mantenimiento, ingreso en efectivo y el terreno gana plusvalía. Un clásico de las familias que sí acumulan patrimonio." },
  { id: "tg-lote-preventa", tipo: "inmueble", subtipo: "depto", titulo: "Lote de 3 departamentos en preventa",
    texto: "La desarrolladora te da descuento por comprar tres unidades juntas.",
    precio: 5400000, enganche: 950000, flujo: 36000, riesgo: "alto",
    nota: "Comprar por volumen baja el precio unitario, pero concentra todo tu riesgo en un solo desarrollo." },
];

/* ------------------------------------------------------------------
   4. GASTOS IMPREVISTOS  ("doodads": lo que te descarrila)
   ------------------------------------------------------------------
   monto      : lo que pagas de contado
   deuda      : opcional { nombre, saldo, pagoMensual } si lo compras a meses
   soloConHijos: la carta solo aplica si tienes hijos
   ------------------------------------------------------------------ */
const GASTOS = [
  { id: "gi-tenencia", titulo: "Tenencia, refrendo y verificación", monto: 4500,
    texto: "Toca renovar placas y pasar la verificación. Y sí, también el holograma." },
  { id: "gi-transmision", titulo: "Se descompuso la transmisión", monto: 18000,
    texto: "El taller te da el diagnóstico y no es barato. Sin coche no llegas a trabajar." },
  { id: "gi-multa", titulo: "Multa de tránsito y corralón", monto: 3200,
    texto: "Te lo llevó la grúa por estacionarte donde no debías." },
  { id: "gi-medico", titulo: "Consulta y estudios sin seguro", monto: 7500,
    texto: "Necesitas estudios de laboratorio y no tienes gastos médicos mayores." },
  { id: "gi-vet", titulo: "Emergencia con el perro", monto: 5500,
    texto: "Se comió un calcetín. Cirugía de urgencia en la veterinaria." },
  { id: "gi-deducible", titulo: "Deducible del seguro tras un choque", monto: 9000,
    texto: "Sin lesionados, pero el deducible es el 5% del valor del auto." },
  { id: "gi-fuga", titulo: "Fuga de agua en la casa", monto: 4200,
    texto: "Llegó un recibo altísimo y hay que romper piso para reparar." },
  { id: "gi-boiler", titulo: "Se murieron el boiler y la bomba", monto: 3800,
    texto: "Dos aparatos el mismo mes. Así funciona la vida." },
  { id: "gi-llantas", titulo: "Juego de llantas nuevas", monto: 7200,
    texto: "Ya estaban lisas y viene temporada de lluvias." },
  { id: "gi-xv", titulo: "XV años de tu sobrina", monto: 6000,
    texto: "Vestido, regalo, salón... y el chambelán te tocó pagarlo a ti." },
  { id: "gi-boda", titulo: "Boda de tu mejor amigo en Vallarta", monto: 12000,
    texto: "Vuelo, hotel y regalo. Decir que no también cuesta." },
  { id: "gi-playa", titulo: "Fin de semana en la playa", monto: 8500,
    texto: "Ya estaban cansados y salió una promoción de última hora." },
  { id: "gi-madres", titulo: "Día de las Madres", monto: 2500,
    texto: "Flores, comida y el regalo. No hay negociación posible." },
  { id: "gi-barda", titulo: "Se cayó la barda por las lluvias", monto: 14000,
    texto: "Material y mano de obra. Y el vecino quiere que la levantes ya." },
  { id: "gi-tramites", titulo: "Trámites: licencia, pasaporte y actas", monto: 1800,
    texto: "Todo se venció el mismo mes." },
  { id: "gi-prestamo-familiar", titulo: "Le prestaste a un familiar", monto: 10000,
    texto: "Prometió pagarte el mes que entra. Los dos saben que no va a pasar." },
  { id: "gi-cel", titulo: "Celular nuevo (se te cayó)", monto: 11000,
    texto: "Pantalla destrozada. Lo pagas de contado para no endeudarte." },
  { id: "gi-cursos-verano", titulo: "Cursos de verano de los niños", monto: 6500, soloConHijos: true,
    texto: "Dos meses sin escuela hay que resolverlos de alguna manera." },
  { id: "gi-utiles", titulo: "Regreso a clases: útiles y uniformes", monto: 5200, soloConHijos: true,
    texto: "Lista de útiles, zapatos, uniformes y la cooperación." },
  { id: "gi-fiesta", titulo: "Fiesta infantil con brincolín", monto: 9000, soloConHijos: true,
    texto: "Pastel, piñata, brincolín y 30 invitados." },

  /* Compras a meses: no solo te sacan efectivo, te dejan una deuda mensual */
  { id: "gi-buenfin-tv", titulo: "El Buen Fin: pantalla a 18 meses", monto: 0,
    deuda: { nombre: "Pantalla a meses (tarjeta)", saldo: 16200, pagoMensual: 900 },
    texto: "\"Son solo 900 pesitos al mes.\" La compras a 18 meses sin intereses.",
    nota: "Los meses sin intereses no son gratis: te comprometen flujo futuro. Cada MSI baja tu capacidad de invertir." },
  { id: "gi-muebles", titulo: "Sala nueva a 24 meses (departamental)", monto: 0,
    deuda: { nombre: "Sala a meses (departamental)", saldo: 21600, pagoMensual: 900 },
    texto: "La sala vieja ya no daba. Firmas el crédito ahí mismo en la tienda.",
    nota: "El crédito departamental es de los más caros del mercado: puede superar el 70% anual." },
  { id: "gi-viaje-msi", titulo: "Viaje familiar a 12 meses", monto: 0,
    deuda: { nombre: "Viaje a meses (tarjeta)", saldo: 30000, pagoMensual: 2500 },
    texto: "Cancún todo incluido, a doce meses con la tarjeta.",
    nota: "Financiar experiencias que se acaban en una semana con deuda de un año es cómo se rompe un presupuesto." },
];

/* ------------------------------------------------------------------
   5. MERCADO
   ------------------------------------------------------------------
   efecto:
     venta          -> ofertas de compra por tus activos (tú decides)
     precioAccion   -> precio para vender un ticker específico
     ajusteFlujo    -> cambia el flujo mensual de ciertos activos
     efectivo       -> cobras o pagas
     perdida        -> pierdes un activo que cumpla el filtro
   filtro: { clase?, subtipo?, subtipos?[], ticker? }
   precio:  { modo: 'masFijo'|'multiplo'|'porcentaje'|'fijo', valor }
   ------------------------------------------------------------------ */
const MERCADO = [
  { id: "mk-comprador-social", efecto: "venta", titulo: "Comprador para casa de interés social",
    texto: "Una familia con crédito Infonavit autorizado quiere una casa como la tuya y paga $150,000 arriba de tu costo.",
    filtro: { clase: "inmueble", subtipos: ["casa"] }, precio: { modo: "masFijo", valor: 150000 },
    nota: "Vender bien también es parte del negocio. Un buen inversionista sabe cuándo tomar la utilidad." },
  { id: "mk-comprador-depto", efecto: "venta", titulo: "Inversionista busca departamentos",
    texto: "Un fondo está comprando departamentos en renta y ofrece $250,000 arriba de lo que pagaste.",
    filtro: { clase: "inmueble", subtipos: ["depto"] }, precio: { modo: "masFijo", valor: 250000 },
    nota: "Cuando venden, ¿pierdes el flujo mensual? Compara la utilidad de una vez contra los años de renta que dejas de cobrar." },
  { id: "mk-nearshoring", efecto: "venta", titulo: "El nearshoring dispara el Bajío",
    texto: "Una armadora busca naves industriales y ofrece 40% arriba del valor de compra por tu bodega.",
    filtro: { clase: "inmueble", subtipos: ["bodega"] }, precio: { modo: "porcentaje", valor: 1.4 },
    nota: "La relocalización de manufactura hacia México disparó el precio del suelo industrial en Querétaro, Guanajuato y Nuevo León." },
  { id: "mk-tren-maya", efecto: "venta", titulo: "Boom turístico en la península",
    texto: "Con el Tren Maya operando, te ofrecen el doble por cualquier terreno que tengas.",
    filtro: { clase: "inmueble", subtipos: ["terreno"] }, precio: { modo: "porcentaje", valor: 2.0 },
    nota: "La plusvalía por infraestructura es real, pero llega en años y no en meses. El que aguanta, gana." },
  { id: "mk-plusvalia-colonia", efecto: "venta", titulo: "Tu colonia se puso de moda",
    texto: "Abrieron cafeterías y una línea de transporte nueva. Te ofrecen $300,000 extra por tu casa o departamento.",
    filtro: { clase: "inmueble", subtipos: ["casa", "depto"] }, precio: { modo: "masFijo", valor: 300000 },
    nota: "Gentrificación: sube el precio y la renta, pero también el predial." },
  { id: "mk-cadena-local", efecto: "venta", titulo: "Cadena comercial quiere tu local",
    texto: "Una tienda de conveniencia busca esquinas y ofrece 25% arriba por tu local o estacionamiento.",
    filtro: { clase: "inmueble", subtipos: ["local", "estacionamiento"] }, precio: { modo: "porcentaje", valor: 1.25 },
    nota: "Los inmuebles comerciales se valúan por el ingreso que producen, no por los metros cuadrados." },
  { id: "mk-socio-negocio", efecto: "venta", titulo: "Un socio quiere comprar tu negocio",
    texto: "Te ofrece 2.5 veces lo que invertiste en cualquier negocio pequeño.",
    filtro: { clase: "negocio" }, precio: { modo: "porcentaje", valor: 2.5 },
    nota: "Un negocio se vende por múltiplos de utilidad. Si te ofrecen menos de 3 años de flujo, piénsalo." },
  { id: "mk-amxl-sube", efecto: "precioAccion", titulo: "AMXL se cotiza en $26",
    texto: "América Móvil sube tras un buen reporte trimestral.", filtro: { ticker: "AMXL" }, precio: { modo: "fijo", valor: 26 } },
  { id: "mk-amxl-baja", efecto: "precioAccion", titulo: "AMXL cae a $11",
    texto: "Presión regulatoria y competencia en tarifas.", filtro: { ticker: "AMXL" }, precio: { modo: "fijo", valor: 11 } },
  { id: "mk-walmex", efecto: "precioAccion", titulo: "WALMEX se cotiza en $88",
    texto: "Ventas mismas tiendas al alza durante el Buen Fin.", filtro: { ticker: "WALMEX" }, precio: { modo: "fijo", valor: 88 } },
  { id: "mk-cemex-baja", efecto: "precioAccion", titulo: "CEMEXCPO cae a $7",
    texto: "Se frena la obra pública y la construcción privada.", filtro: { ticker: "CEMEXCPO" }, precio: { modo: "fijo", valor: 7 },
    nota: "Cuando una buena empresa cae por el ciclo (no por su negocio), suele ser momento de comprar, no de vender." },
  { id: "mk-cemex-sube", efecto: "precioAccion", titulo: "CEMEXCPO se dispara a $28",
    texto: "Nuevo plan de infraestructura y demanda récord de cemento.", filtro: { ticker: "CEMEXCPO" }, precio: { modo: "fijo", valor: 28 } },
  { id: "mk-naftrac", efecto: "precioAccion", titulo: "El IPC en máximos: NAFTRAC a $92",
    texto: "La bolsa mexicana toca máximos históricos.", filtro: { ticker: "NAFTRAC" }, precio: { modo: "fijo", valor: 92 } },
  { id: "mk-funo", efecto: "precioAccion", titulo: "FUNO11 sube a $34",
    texto: "Banxico baja tasas y las FIBRAs se ponen atractivas otra vez.", filtro: { ticker: "FUNO11" }, precio: { modo: "fijo", valor: 34 },
    nota: "Cuando bajan las tasas, los activos que pagan renta suben de precio. Y al revés." },
  { id: "mk-gapb", efecto: "precioAccion", titulo: "GAPB se cotiza en $470",
    texto: "Tráfico de pasajeros récord en Los Cabos y Guadalajara.", filtro: { ticker: "GAPB" }, precio: { modo: "fijo", valor: 470 } },
  { id: "mk-btc", efecto: "precioAccion", titulo: "El ETF de bitcoin (IBIT) llega a $3,200",
    texto: "Euforia en el mercado cripto.", filtro: { ticker: "IBIT" }, precio: { modo: "fijo", valor: 3200 },
    nota: "En activos sin flujo, la única forma de ganar es que alguien pague más que tú. Vender a tiempo es todo." },
  { id: "mk-btc-baja", efecto: "precioAccion", titulo: "El ETF de bitcoin (IBIT) se desploma a $420",
    texto: "Corrección brutal del mercado cripto.", filtro: { ticker: "IBIT" }, precio: { modo: "fijo", valor: 420 } },
  { id: "mk-volar", efecto: "precioAccion", titulo: "VOLARA se cotiza en $24",
    texto: "Rutas nuevas y turbosina barata.", filtro: { ticker: "VOLARA" }, precio: { modo: "fijo", valor: 24 } },
  { id: "mk-banxico-sube", efecto: "ajusteFlujo", titulo: "Banxico sube la tasa de referencia",
    texto: "Tus inversiones de renta fija empiezan a pagar 20% más.",
    filtro: { clase: "renta-fija" }, factor: 1.2,
    nota: "La tasa de referencia mueve CETES, pagarés y créditos. Sube: gana el ahorrador, sufre el endeudado." },
  { id: "mk-banxico-baja", efecto: "ajusteFlujo", titulo: "Banxico recorta la tasa de referencia",
    texto: "Tus CETES y pagarés rinden 20% menos al renovarse.",
    filtro: { clase: "renta-fija" }, factor: 0.8,
    nota: "Nadie te avisa cuando cambian las tasas: por eso conviene tener también activos que suban con la inflación." },
  { id: "mk-ley-rentas", efecto: "ajusteFlujo", titulo: "Ajuste anual de rentas por inflación",
    texto: "Tus contratos permiten subir la renta 8% este año.",
    filtro: { clase: "inmueble" }, factor: 1.08,
    nota: "Un contrato con cláusula de ajuste por inflación protege tu flujo real. Siempre inclúyela." },
  { id: "mk-inquilino", efecto: "ajusteFlujo", titulo: "Inquilino moroso y vacancia",
    texto: "Un inquilino deja de pagar y tienes que bajar la renta para volver a colocar el inmueble: -15% de flujo.",
    filtro: { clase: "inmueble" }, factor: 0.85,
    nota: "La vacancia es el riesgo más subestimado en bienes raíces. Presupuesta al menos un mes vacío al año." },
  { id: "mk-crowdfunding-cae", efecto: "perdida", titulo: "Se cae un proyecto de crowdfunding",
    texto: "La plataforma reporta que el desarrollo se detuvo y pierdes lo invertido en crowdfunding.",
    filtro: { origen: "tp-crowdfunding" },
    nota: "Por esto se diversifica: nunca pongas en un solo proyecto dinero que te duela perder." },
  { id: "mk-compadre-no-paga", efecto: "perdida", titulo: "Tu compadre dejó de pagarte",
    texto: "Cerró el taller y desapareció. Pierdes el préstamo que le hiciste.",
    filtro: { origen: "tp-prestamo-compadre" },
    nota: "Prestarle a un conocido casi siempre cuesta el dinero y la relación." },
  { id: "mk-sat-devolucion", efecto: "efectivo", titulo: "El SAT te devuelve tu saldo a favor",
    texto: "Presentaste tu declaración anual con deducciones personales y te devuelven.",
    monto: 12000,
    nota: "Colegiaturas, gastos médicos, funerarios, transporte escolar e intereses hipotecarios son deducibles. Pide factura." },
  { id: "mk-ptu", efecto: "efectivo", titulo: "Reparto de utilidades (PTU) y aguinaldo",
    texto: "Te toca reparto de utilidades. Recibes el equivalente a medio mes de sueldo.",
    modo: "salario", factor: 0.5,
    nota: "El dinero extra es la mejor oportunidad para invertir: no está comprometido en tu presupuesto mensual." },
  { id: "mk-predial", efecto: "efectivo", titulo: "Predial anual de tus propiedades",
    texto: "Pagas el predial de cada inmueble que tienes.",
    modo: "porInmueble", monto: -6000,
    nota: "El predial, el seguro y el mantenimiento se te olvidan al calcular el rendimiento... hasta que llegan." },
  { id: "mk-sismo", efecto: "efectivo", titulo: "Sismo: reparaciones estructurales",
    texto: "Un sismo daña tus inmuebles y hay que reparar.",
    modo: "porInmueble", monto: -18000,
    nota: "Sin seguro de daños, un evento se lleva años de flujo. Asegura lo que no puedas reponer." },
  { id: "mk-herencia", efecto: "efectivo", titulo: "Herencia de un tío",
    texto: "Un tío te dejó un dinerito. La familia por fin se puso de acuerdo.",
    monto: 60000,
    nota: "El dinero inesperado suele evaporarse. Decide a qué activo va ANTES de que caiga a tu cuenta." },
];

/* ------------------------------------------------------------------
   6. TABLERO (Carrera de la Rata) · 24 casillas
   ------------------------------------------------------------------ */
const TABLERO = [
  { tipo: "oportunidad" }, { tipo: "gasto" },   { tipo: "oportunidad" }, { tipo: "caridad" },
  { tipo: "oportunidad" }, { tipo: "pago" },    { tipo: "oportunidad" }, { tipo: "mercado" },
  { tipo: "pago" },        { tipo: "gasto" },   { tipo: "oportunidad" }, { tipo: "pago" },
  { tipo: "oportunidad" }, { tipo: "mercado" }, { tipo: "oportunidad" }, { tipo: "bebe" },
  { tipo: "oportunidad" }, { tipo: "pago" },    { tipo: "oportunidad" }, { tipo: "mercado" },
  { tipo: "pago" },        { tipo: "recorte" }, { tipo: "oportunidad" }, { tipo: "pago" },
];

const CASILLAS = {
  oportunidad: { nombre: "Oportunidad", corto: "Oport.", emoji: "💡", color: "#22c55e" },
  gasto:       { nombre: "Gasto imprevisto", corto: "Gasto", emoji: "💸", color: "#f97316" },
  caridad:     { nombre: "Caridad", corto: "Caridad", emoji: "🤝", color: "#a78bfa" },
  pago:        { nombre: "Día de pago", corto: "Pago", emoji: "💰", color: "#eab308" },
  mercado:     { nombre: "El mercado", corto: "Mercado", emoji: "📈", color: "#38bdf8" },
  bebe:        { nombre: "¡Bebé!", corto: "Bebé", emoji: "👶", color: "#f472b6" },
  recorte:     { nombre: "Recorte de personal", corto: "Recorte", emoji: "📉", color: "#ef4444" },
};

/* ------------------------------------------------------------------
   7. VÍA RÁPIDA
   ------------------------------------------------------------------ */
const VIA_RAPIDA_TABLERO = [
  { tipo: "negocio" }, { tipo: "flujo" },  { tipo: "sueno" },   { tipo: "negocio" },
  { tipo: "caridad" }, { tipo: "negocio" },{ tipo: "flujo" },   { tipo: "contratiempo" },
  { tipo: "negocio" }, { tipo: "sueno" },  { tipo: "negocio" }, { tipo: "flujo" },
  { tipo: "bono" },    { tipo: "negocio" },{ tipo: "sueno" },   { tipo: "contratiempo" },
  { tipo: "negocio" }, { tipo: "flujo" },  { tipo: "negocio" }, { tipo: "sueno" },
  { tipo: "bono" },    { tipo: "negocio" },{ tipo: "flujo" },   { tipo: "contratiempo" },
];

const CASILLAS_VR = {
  negocio:      { nombre: "Gran negocio", corto: "Negocio", emoji: "🏢", color: "#22c55e" },
  sueno:        { nombre: "Tu sueño", corto: "Sueño", emoji: "⭐", color: "#eab308" },
  flujo:        { nombre: "Día de flujo", corto: "Flujo", emoji: "💵", color: "#38bdf8" },
  caridad:      { nombre: "Caridad", corto: "Caridad", emoji: "🤝", color: "#a78bfa" },
  contratiempo: { nombre: "Contratiempo", corto: "Ups", emoji: "⚠️", color: "#ef4444" },
  bono:         { nombre: "Bono", corto: "Bono", emoji: "🎁", color: "#f472b6" },
};

const NEGOCIOS_VR = [
  { id: "vr-parque", titulo: "Parque industrial en Nuevo León", precio: 22000000, flujo: 210000,
    texto: "Naves para proveedores de la industria automotriz, rentadas en dólares." },
  { id: "vr-gimnasios", titulo: "Cadena de 5 gimnasios", precio: 12000000, flujo: 118000,
    texto: "Membresías recurrentes en zonas de clase media." },
  { id: "vr-torre", titulo: "Torre de 40 departamentos", precio: 38000000, flujo: 340000,
    texto: "Edificio completo en renta con administración profesional." },
  { id: "vr-cafeterias", titulo: "Cadena de cafeterías de especialidad", precio: 9000000, flujo: 84000,
    texto: "Ocho sucursales con marca propia y tostaduría." },
  { id: "vr-hotel-cabos", titulo: "Hotel de 60 habitaciones en Los Cabos", precio: 45000000, flujo: 420000,
    texto: "Ocupación alta todo el año y tarifas en dólares." },
  { id: "vr-solar", titulo: "Planta solar con contrato de suministro", precio: 30000000, flujo: 270000,
    texto: "Contrato a 20 años con un consorcio industrial." },
  { id: "vr-colegio", titulo: "Colegio privado bilingüe", precio: 18000000, flujo: 165000,
    texto: "Colegiaturas recurrentes y lista de espera." },
  { id: "vr-abarrotes", titulo: "Distribuidora de abarrotes regional", precio: 15000000, flujo: 140000,
    texto: "Ruta de reparto a 900 tienditas." },
  { id: "vr-logistica", titulo: "Centro logístico de última milla", precio: 26000000, flujo: 245000,
    texto: "Bodega y flotilla rentadas a plataformas de comercio electrónico." },
  { id: "vr-farmacias", titulo: "Cadena de 12 farmacias", precio: 20000000, flujo: 185000,
    texto: "Genéricos y consultorio adyacente en cada sucursal." },
  { id: "vr-clinica", titulo: "Clínica de especialidades", precio: 28000000, flujo: 255000,
    texto: "Quirófanos rentados a médicos y convenios con aseguradoras." },
  { id: "vr-fondo", titulo: "Fondo inmobiliario privado (socio)", precio: 16000000, flujo: 150000,
    texto: "Coinviertes con un desarrollador con historial de 15 años." },
];

const SUENOS_VR = [
  { id: "sn-bacalar", titulo: "Casa frente a la laguna en Bacalar", precio: 8000000, texto: "Despertar viendo el agua de siete colores." },
  { id: "sn-mundo", titulo: "Dar la vuelta al mundo en un año", precio: 3500000, texto: "Sin itinerario fijo, con toda la familia." },
  { id: "sn-escuela", titulo: "Fundar una escuela en tu comunidad", precio: 6000000, texto: "Que otros niños tengan lo que a ti te costó." },
  { id: "sn-rancho", titulo: "Rancho en Jalisco con caballos", precio: 9000000, texto: "Tierra, caballos y silencio." },
  { id: "sn-hijos", titulo: "Que tus hijos estudien sin deudas", precio: 2500000, texto: "Carrera completa pagada, sin crédito educativo." },
  { id: "sn-motorhome", titulo: "Recorrer México en casa rodante", precio: 2000000, texto: "De Baja California a Chiapas, sin prisa." },
  { id: "sn-papas", titulo: "Retiro digno para tus papás", precio: 4000000, texto: "Que dejen de trabajar y no les falte nada." },
  { id: "sn-despacho", titulo: "Abrir tu propio despacho soñado", precio: 5000000, texto: "Tu nombre en la puerta y tu propio equipo." },
  { id: "sn-sabatico", titulo: "Año sabático con tu familia", precio: 3000000, texto: "Doce meses sin alarma ni juntas." },
  { id: "sn-maestria", titulo: "Maestría en el extranjero", precio: 4500000, texto: "Estudiar afuera, con todo pagado." },
  { id: "sn-bodas-oro", titulo: "Bodas de oro de tus papás por todo lo alto", precio: 1500000, texto: "Toda la familia reunida, sin escatimar." },
  { id: "sn-fundacion", titulo: "Fundación para becar jóvenes", precio: 7000000, texto: "Un patrimonio que reparte becas cada año." },
];

const CONTRATIEMPOS_VR = [
  { id: "ct-sat", titulo: "Auditoría del SAT", texto: "Créditos fiscales y honorarios de tu contador.", modo: "fijo", monto: 800000 },
  { id: "ct-demanda", titulo: "Demanda laboral colectiva", texto: "Te toca liquidar y pagar abogados.", modo: "fijo", monto: 1200000 },
  { id: "ct-divorcio", titulo: "Divorcio", texto: "Se divide el patrimonio: pierdes la mitad de tu efectivo.", modo: "mitadEfectivo" },
  { id: "ct-fraude", titulo: "Un socio te defrauda", texto: "Pierdes uno de tus grandes negocios.", modo: "pierdeNegocio" },
  { id: "ct-crisis", titulo: "Crisis económica", texto: "Todos tus negocios bajan 20% su flujo por un tiempo.", modo: "ajusteFlujo", factor: 0.8 },
];

const BONOS_VR = [
  { id: "bn-venta", titulo: "Vendes una participación", texto: "Un fondo te compra una parte pequeña de un negocio.", monto: 2000000 },
  { id: "bn-dividendo", titulo: "Dividendo extraordinario", texto: "Uno de tus negocios reparte utilidades acumuladas.", monto: 1500000 },
  { id: "bn-plusvalia", titulo: "Plusvalía por infraestructura", texto: "Una obra pública dispara el valor de tus terrenos.", monto: 3000000 },
];

/* ------------------------------------------------------------------
   8. GLOSARIO (la parte de "repasar escenarios financieros")
   ------------------------------------------------------------------ */
const GLOSARIO = [
  { t: "Flujo de efectivo (cashflow)", d: "Lo que te queda cada mes después de pagar todo. Es el número que decide si eres libre o no: mientras tu flujo pasivo no cubra tus gastos, dependes de tu trabajo." },
  { t: "Ingreso pasivo", d: "Dinero que entra sin que tú trabajes ese mes: rentas, dividendos, intereses, utilidades de un negocio que operan otros. Es el marcador real del juego." },
  { t: "Activo vs. pasivo", d: "Activo es lo que te pone dinero en la bolsa; pasivo es lo que te lo saca. Tu casa donde vives, con hipoteca, saca dinero cada mes: contablemente es un activo, pero en flujo se comporta como pasivo." },
  { t: "Infonavit / Cofinavit", d: "Crédito de vivienda que se descuenta de tu nómina. Tasa baja comparada con la banca, pero se paga en 20 o 30 años. Cofinavit combina tu subcuenta con un crédito bancario para alcanzar montos mayores." },
  { t: "CETES", d: "Certificados de la Tesorería: deuda del gobierno federal a 28, 91, 182 o 364 días. Se compran desde $100 en cetesdirecto. Lo más seguro que puedes tener en pesos." },
  { t: "Pagaré bancario", d: "Le prestas al banco a plazo fijo (7, 28, 90 días) a cambio de una tasa. Cómodo, pero casi siempre paga menos que CETES." },
  { t: "Udibonos", d: "Bonos ligados a UDIs, es decir, a la inflación. Protegen tu poder de compra en el largo plazo." },
  { t: "FIBRA", d: "Fideicomiso de Infraestructura y Bienes Raíces. Cotiza en la bolsa y está obligado a repartir al menos el 95% de su resultado fiscal. Bienes raíces sin escrituras ni inquilinos." },
  { t: "Meses sin intereses (MSI)", d: "No cobran interés, pero comprometen tu flujo futuro. Cada MSI que firmas reduce cuánto puedes invertir los próximos meses." },
  { t: "Crédito departamental", d: "El de Coppel, Elektra y similares. Es de los créditos más caros que existen en México: el CAT puede pasar del 70% anual." },
  { t: "Fonacot", d: "Crédito para trabajadores formales que se descuenta vía nómina. Más barato que una tarjeta, pero sigue siendo deuda de consumo." },
  { t: "CAT", d: "Costo Anual Total: el costo real de un crédito incluyendo intereses, comisiones y seguros. Es el único número que sirve para comparar dos créditos." },
  { t: "RESICO", d: "Régimen Simplificado de Confianza del SAT: para personas físicas con ingresos hasta 3.5 millones al año, con tasas bajísimas (1% a 2.5%). Clave si tienes negocio o facturas por tu cuenta." },
  { t: "PTU", d: "Reparto de utilidades: el 10% de la utilidad fiscal de tu empresa se reparte entre los trabajadores, normalmente en mayo. Dinero extra ideal para invertir." },
  { t: "Enganche y apalancamiento", d: "Con $200,000 de enganche controlas un inmueble de $1,000,000: el banco pone el resto. El apalancamiento multiplica tus ganancias... y también tus pérdidas." },
  { t: "Rendimiento sobre el enganche", d: "Flujo anual ÷ dinero que pusiste. Si un depto te deja $2,400 al mes con $230,000 de enganche, es 12.5% anual sobre tu dinero. Ese es el número que debes comparar contra CETES." },
  { t: "Vacancia", d: "Los meses en que tu inmueble está vacío. Presupuesta al menos uno al año: si no lo haces, tu rendimiento real es menor al que calculaste." },
  { t: "Fondo de emergencia", d: "De 3 a 6 meses de gastos en un instrumento líquido (fondo de deuda o CETES a 28 días). Es lo que evita que un imprevisto te obligue a endeudarte con tarjeta." },
  { t: "Diversificación", d: "No poner todo en un solo activo, ni en una sola clase. En este juego se ve claro: quien tiene renta fija, bolsa e inmuebles aguanta las cartas malas." },
  { t: "Los rendimientos de este juego", d: "Los tratos del mazo son deliberadamente buenos, para que una partida dure minutos y no meses: un inmueble apalancado aquí rinde 30-45% anual sobre el enganche. En la vida real un buen inmueble en renta da 8-12% anual sobre el precio, y 15-25% sobre tu dinero si lo apalancas con cabeza. La renta fija del juego (CETES, pagarés) sí está a tasas reales: por eso se siente lenta. Si afuera te ofrecen 45% garantizado, revisa dos veces." },
  { t: "Salir de la carrera de la rata", d: "Cuando tu ingreso pasivo supera tus gastos totales. A partir de ahí trabajas porque quieres, no porque necesitas." },
];

CF.DATOS = {
  PROFESIONES, TRATOS_PEQUENOS, TRATOS_GRANDES, GASTOS, MERCADO,
  TABLERO, CASILLAS, VIA_RAPIDA_TABLERO, CASILLAS_VR,
  NEGOCIOS_VR, SUENOS_VR, CONTRATIEMPOS_VR, BONOS_VR, GLOSARIO,
};
